(()=>{
const DATA=window.QUESTION_DATA,STORE='chugaku-september-v2',OLD='chugaku-september-v1',app=document.querySelector('#app');let S={};
const esc=x=>String(x??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const base=()=>({version:2,history:[],mistakes:{},progress:{}});function load(){try{let d=JSON.parse(localStorage.getItem(STORE)||'null');if(d)return {...base(),...d,progress:d.progress||{}};d=JSON.parse(localStorage.getItem(OLD)||'null');if(d){d={...base(),history:d.history||[],mistakes:d.mistakes||{}};localStorage.setItem(STORE,JSON.stringify(d));return d}}catch(e){}return base()}const save=d=>localStorage.setItem(STORE,JSON.stringify(d));
const st=id=>load().progress[id]||{attempts:0,correct:0,wrong:0,lastCorrect:null,streak:0},rate=p=>p.attempts?Math.round(100*p.correct/p.attempts):null,weak=p=>p.attempts&&p.streak<2&&(p.lastCorrect===false||p.wrong>=2||p.correct/p.attempts<.6);
const head=(back=1)=>`<header><div>${back?'<button class="back" data-go="home">‹</button>':'<span class="mark">中</span>'}<div><strong>中1 9月中間対策</strong><small>英語・社会（歴史）</small></div></div><button class="history-button" data-go="dash">学習記録</button></header>`;
function unitStats(k){let d=load();return [...new Set(DATA[k].questions.map(q=>q.unit))].map(u=>{let ps=DATA[k].questions.filter(q=>q.unit===u).map(q=>d.progress[q.id]).filter(Boolean),a=ps.reduce((n,x)=>n+x.attempts,0),c=ps.reduce((n,x)=>n+x.correct,0);return {u,a,c,r:a?Math.round(c/a*100):null}})}
function home(){let d=load(),w=Object.values(DATA).flatMap(x=>x.questions).filter(q=>weak(d.progress[q.id]||st(q.id))).length;app.innerHTML=`${head(0)}<section class="hero"><p>模試 → 弱点発見 → 理解 → 解き直し</p><h1>今日の学習を選ぼう</h1><span class="range-note">記録はこの端末だけに保存されます</span></section><section class="home-section"><h2>教科を選ぶ</h2>${['english','social'].map(k=>{let s=DATA[k];return `<button class="subject-card ${s.color}" data-subject="${k}"><span class="subject-icon">${k==='english'?'A':'歴'}</span><span><b>${s.name}</b><small>${esc(s.range)}</small></span><span class="arrow">›</span></button>`}).join('')}</section><section class="quick"><h2>復習・記録</h2><div class="quick-grid"><button data-go="weak"><b>苦手を特訓</b><small>${w?`${w}問から最大10問`:'まだ苦手問題はありません'}</small></button><button data-go="dash"><b>学習記録</b><small>単元別の正答率を見る</small></button></div></section><p class="privacy">満点を取ったら、お祝いページをスクショしてパパに送ろう！</p>`}
function choose(k){S.subject=k;let s=DATA[k],w=s.questions.filter(q=>weak(st(q.id))).length;app.innerHTML=`${head()}<section class="subject-page"><span class="pill ${s.color}">${s.name}</span><h1>${s.name}を学習する</h1><p>${esc(s.range)}</p><div class="action-stack"><button class="big-action primary ${s.color}" data-start="exam"><span>模擬試験</span><small>全${s.questions.length}問・自動採点・解説つき</small><b>はじめる ›</b></button><button class="big-action" data-start="weak"><span>苦手を特訓</span><small>${w?`${w}問から最大10問を自動出題`:'苦手問題はまだありません'}</small><b>›</b></button></div><h2>単元を指定して復習</h2><div class="unit-list">${unitStats(k).map(x=>`<button data-unit="${esc(x.u)}"><b>${esc(x.u)}</b><small>${x.r===null?'まだ記録なし':`正答率 ${x.r}%（${x.c}/${x.a}）`}</small><span>›</span></button>`).join('')}</div></section>`}
function weakHome(){let d=load();app.innerHTML=`${head()}<section class="list-page"><h1>苦手を特訓</h1><p>正解率60%未満・前回不正解・複数回不正解の問題を集めます。2回連続正解で卒業です。</p>${Object.entries(DATA).map(([k,s])=>{let n=s.questions.filter(q=>weak(d.progress[q.id]||st(q.id))).length;return `<button class="review-card" data-weak-subject="${k}"><span class="subject-icon ${s.color}">${k==='english'?'A':'歴'}</span><span><b>${s.name}</b><small>${n?`${n}問から最大10問を出題`:'今は苦手問題がありません'}</small></span><b>›</b></button>`}).join('')}</section>`}
function start(kind,k=S.subject,u){let qs=DATA[k].questions;if(kind==='weak')qs=qs.filter(q=>weak(st(q.id))).slice(0,10);if(u)qs=qs.filter(q=>q.unit===u);if(!qs.length){alert('まだ対象の問題はありません。先に模擬試験をしてみよう！');return choose(k)}S={subject:k,questions:qs,current:0,answers:{},kind};question()}
function question(){let q=S.questions[S.current],a=S.answers[q.id],n=S.current+1,p=st(q.id),label=p.attempts?`正解率 ${rate(p)}%（${p.correct}/${p.attempts}）${p.lastCorrect===false?'　★ 前回間違えた問題':''}`:'初出題';app.innerHTML=`${head()}<section class="quiz"><div class="quiz-top"><span>${DATA[S.subject].name}・${S.kind==='exam'?'模擬試験':S.kind==='weak'?'苦手特訓':'単元復習'}</span><span>${n} / ${S.questions.length}</span></div><div class="progress"><i style="width:${Math.round((n-1)/S.questions.length*100)}%"></i></div><span class="unit">${esc(q.unit)}・${esc(q.level)}</span><p class="question-history">${esc(label)}</p><h1>${esc(q.text)}</h1><div class="choices">${q.choices.map((c,i)=>`<button class="choice ${a===i?'selected':''}" data-answer="${i}"><b>${'アイウエ'[i]}</b><span>${esc(c)}</span></button>`).join('')}</div><div class="quiz-nav"><button class="subtle" data-prev ${S.current===0?'disabled':''}>前へ</button><button class="next" data-next ${a===undefined?'disabled':''}>${n===S.questions.length?'採点する':'次へ'}</button></div></section>`}
function diagram(q){if(!q.diagram)return '';let x={civilizations:'<b>四大文明</b><span>エジプト<br><i>ナイル川</i></span><span>メソポタミア<br><i>チグリス・ユーフラテス川</i></span><span>インダス<br><i>インダス川</i></span><span>中国<br><i>黄河</i></span>',shotoku:'<b>聖徳太子（厩戸王）</b><span>冠位十二階</span><span>十七条の憲法</span><span>遣隋使 → 小野妹子 → 隋</span>',nara:'<b>飛鳥 → 奈良</b><span>645 大化の改新</span><span>701 大宝律令</span><span>710 平城京</span><span>聖武天皇 → 東大寺・大仏</span>'}[q.diagram];return `<div class="diagram">${x}</div>`}
function finish(){let d=load(),ok=[];S.questions.forEach(q=>{let yes=S.answers[q.id]===q.answer;if(yes)ok.push(q);let p=d.progress[q.id]||{attempts:0,correct:0,wrong:0,lastCorrect:null,streak:0};p.attempts++;p.lastCorrect=yes;if(yes){p.correct++;p.streak++}else{p.wrong++;p.streak=0}d.progress[q.id]=p});let score=Math.round(ok.length/S.questions.length*100),wrong=S.questions.filter(q=>!ok.includes(q)).map(q=>q.id);d.mistakes[S.subject]=[...new Set([...(d.mistakes[S.subject]||[]),...wrong])].filter(id=>!ok.some(q=>q.id===id));d.history.unshift({date:new Date().toISOString(),subject:S.subject,subjectName:DATA[S.subject].name,score,total:S.questions.length,correct:ok.length});save(d);S.result={ok,score};score===100?celebrate():result()}
function result(){let {ok,score}=S.result;app.innerHTML=`${head()}<section class="result"><div class="score-ring"><span>${score}</span><small>点</small></div><h1>${score>=80?'よくできました！':score>=60?'あと一歩。復習で伸ばそう！':'基本をもう一度確認しよう！'}</h1><p>${ok.length} / ${S.questions.length} 問正解</p>${ok.length<S.questions.length?'<button class="review-cta" data-start="weak">苦手を特訓する</button>':''}<h2>答えと参考書解説</h2><div class="explanations">${S.questions.map((q,i)=>`<article class="explanation ${ok.includes(q)?'ok':'ng'}"><div><b>${i+1}. ${ok.includes(q)?'正解':'まちがい'}</b><span>${esc(q.unit)}</span></div><p>${esc(q.text)}</p><p class="answer">あなた：${esc(q.choices[S.answers[q.id]])}<br>正解：${esc(q.choices[q.answer])}</p><p>${esc(q.explanation)}</p><p class="memory"><b>覚えるポイント：</b>${esc(q.point||q.explanation)}</p>${diagram(q)}<button class="check-button" data-check="${q.id}">解説から確認問題をする ›</button></article>`).join('')}</div><button class="home-bottom" data-go="home">ホームへ戻る</button></section>`}
function check(id){let q=Object.values(DATA).flatMap(x=>x.questions).find(x=>x.id===id),c=q.check||{text:q.text,choices:q.choices,answer:q.answer,explanation:q.explanation};S.check=c;app.innerHTML=`${head()}<section class="quiz"><span class="unit">解説から確認問題</span><h1>${esc(c.text)}</h1><div class="choices">${c.choices.map((x,i)=>`<button class="choice" data-check-answer="${i}"><b>${'アイウエ'[i]}</b><span>${esc(x)}</span></button>`).join('')}</div></section>`}function checkAnswer(i){let good=+i===S.check.answer;app.innerHTML=`${head()}<section class="result"><div class="check-result ${good?'ok':'ng'}">${good?'✓ 理解できました！':'もう一度、解説を見てみよう'}</div><p>${esc(S.check.explanation)}</p><button class="review-cta" data-go="result">答えと解説へ戻る</button></section>`}
function celebrate(){app.innerHTML=`${head(0)}<section class="celebrate"><div class="confetti">★　✦　★</div><p>満点達成！</p><h1>100点おめでとう！</h1><div class="hundred">100<span>点</span></div><p>がんばりが実を結んだね。すばらしい！</p><div class="send-note"><b>このページをスクショして<br>パパに送ってね</b><small>スクショと引き換えに、ご褒美をもらおう！</small></div><button class="home-bottom" data-go="home">ホームへ戻る</button></section>`}
function dash(){let d=load();app.innerHTML=`${head()}<section class="list-page"><h1>学習記録</h1><p>正答率は、これまでの回答すべてから計算しています。</p>${Object.entries(DATA).map(([k,s])=>`<h2 class="dash-title">${s.name}</h2><div class="stats-list">${unitStats(k).map(x=>`<button data-subject="${k}" data-unit="${esc(x.u)}"><b>${esc(x.u)}</b><span>${x.r===null?'未挑戦':`正答率 ${x.r}%（${x.c}/${x.a}）`}</span><i style="width:${x.r||0}%"></i></button>`).join('')}</div>`).join('')}<h2>模試の記録</h2>${d.history.length?`<div class="history-list">${d.history.slice(0,12).map(x=>`<article><span class="date">${new Date(x.date).toLocaleDateString('ja-JP',{month:'numeric',day:'numeric'})}</span><b>${x.subjectName}</b><span>${x.correct}/${x.total}問</span><strong>${x.score}点</strong></article>`).join('')}</div>`:'<div class="empty">まだ記録がありません。</div>'}</section>`}
app.addEventListener('click',e=>{let b=e.target.closest('button');if(!b)return;if(b.dataset.go){if(b.dataset.go==='home')return home();if(b.dataset.go==='dash')return dash();if(b.dataset.go==='weak')return weakHome();return result()}if(b.dataset.weakSubject)return start('weak',b.dataset.weakSubject);if(b.dataset.subject&&b.dataset.unit)return start('unit',b.dataset.subject,b.dataset.unit);if(b.dataset.subject)return choose(b.dataset.subject);if(b.dataset.unit)return start('unit',S.subject,b.dataset.unit);if(b.dataset.start)return start(b.dataset.start);if(b.dataset.answer!==undefined){S.answers[S.questions[S.current].id]=+b.dataset.answer;return question()}if(b.dataset.prev!==undefined){S.current--;return question()}if(b.dataset.next!==undefined)return S.current===S.questions.length-1?finish():(S.current++,question());if(b.dataset.check)return check(b.dataset.check);if(b.dataset.checkAnswer!==undefined)return checkAnswer(b.dataset.checkAnswer)});if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));home();
})();
